[metadata]
name = linux-harden
version = 0.1.0

[options]
packages = find:
install_requires =
    typer[all]>=0.9
    pyyaml>=6.0
python_requires = >=3.10

[options.extras_require]
dev =
    pytest
    pytest-mock

[flake8]
max-line-length = 100
extend-ignore = E203, W503

[isort]
profile = black

[tool:pytest]
testpaths = tests
addopts = -ra
